[package]
name = "leetcode"
description = "Some LeetCode solutions"
edition = "2021"
authors = ["Andreas Waidler <lintermute@mailbox.org>"]
license = "MIT OR Apache-2.0"
version = "0.0.0"
publish = false

[dev-dependencies]
test-case = { workspace = true }
